version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'mongo-container'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPassXXX
    volumes:
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    ports:
      - '27017:27017'